apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lra1nbmbd-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/lra1nbmbd-java-quarkus